VANRES = 'vanilla resistance'
MERLIN = 'Merlin'
PERCIVAL = 'Percival'
RESROLES = (VANRES, MERLIN, PERCIVAL)
VANSPY = 'vanilla spy'
ASSASSIN = 'assassin'
MORGANA = 'Morgana'
MORDRED = 'Mordred'
MORDASS = 'Mordred/Assassin'
OBERON = 'Oberon'
SPYROLES = (VANSPY, ASSASSIN, MORGANA, MORDRED, MORDASS, OBERON)
